# Generated by Django 4.0.3 on 2024-04-01 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumer_type', models.CharField(choices=[('COMERCIAL', 'Comercial'), ('RESIDENCIAL', 'Residencial'), ('INDUSTRIAL', 'Industrial')], max_length=128, verbose_name='Tipo de Consumidor')),
                ('consumption_range', models.CharField(choices=[('< 10.000 kWh', '< 10.000 kWh'), ('>= 10.000 kWh e <= 20.000 kWh', '>= 10.000 kWh e <= 20.000 kWh'), ('> 20.000 kWh', '> 20.000 kWh')], max_length=128, verbose_name='Faixa de Consumo')),
                ('cover_value', models.CharField(choices=[('90%', '90%'), ('95%', '95%'), ('99%', '99%')], max_length=128, verbose_name='Cobertura')),
                ('discount_value', models.FloatField(verbose_name='Desconto')),
            ],
        ),
    ]
