# Generated by Django 4.0.3 on 2024-04-01 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_discountrules'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumer',
            name='discount_rule',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='discount_rule', to='calculator.discountrules'),
            preserve_default=False,
        ),
    ]
