# Generated by Django 4.0.3 on 2024-04-01 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0005_alter_consumer_discount_rule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consumer',
            options={'verbose_name': 'Consumidor', 'verbose_name_plural': 'Consumidors'},
        ),
        migrations.AlterModelOptions(
            name='discountrules',
            options={'verbose_name': 'Desconto', 'verbose_name_plural': 'Descontos'},
        ),
        migrations.AddField(
            model_name='discountrules',
            name='percentage_discount',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Desconto Percentual'),
        ),
    ]
